FROM lonelyplanet/scala

RUN apt-get update && apt-get install -y --no-install-recommends python python-setuptools python-pip
RUN pip install --upgrade pip
RUN pip install requests jsonschema termcolor rfc3987 attrs
